spring.application.name=notification-service

clients.user-service.base-url=http://localhost:8081

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=

notification-service.mail.from=incident-system@example.local

server.port=8082
