package ru.bmstu.notificationservice.enums;

public enum ResponsibleService {
    HARDWARE_SERVICE,
    ADMINISTRATORS_SERVICE,
    PRINTING_SERVICE,
    DEVOPS_SERVICE,
    DEVELOPMENT_SERVICE,
    FACILITIES_SERVICE,
    PROCUREMENT_SERVICE,
    WAREHOUSE_SERVICE
}
