spring.application.name=incident-service

spring.datasource.url=jdbc:postgresql://localhost:5432/incident_db
spring.datasource.username=incident_user
spring.datasource.password=incident_password

spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
