spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=user_user
spring.datasource.password=user_password

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
